[package]
name = "sqcorsslib"
version = "0.1.1"
edition = "2021"
description = "Ramadab training 2022"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
